-- MySQL Script generated by MySQL Workbench
-- 07/21/15 19:51:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inix6848_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inix6848_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inix6848_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `inix6848_db` ;

-- -----------------------------------------------------
-- Table `inix6848_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inix6848_db`.`user` (
  `id_user` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `registered` DATETIME NOT NULL,
  `lastlogin` DATETIME NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inix6848_db`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inix6848_db`.`article` (
  `id_article` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `img` VARCHAR(45) NULL,
  `category` VARCHAR(45) NOT NULL,
  `postdate` DATETIME NOT NULL,
  `published` VARCHAR(1) NOT NULL DEFAULT 'N',
  `recommended` VARCHAR(1) NOT NULL DEFAULT 'N',
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_article`),
  INDEX `fk_article_user_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_article_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `inix6848_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inix6848_db`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inix6848_db`.`staff` (
  `id_staff` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `bio` VARCHAR(600) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `division` VARCHAR(45) NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_staff`),
  INDEX `fk_staff_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_staff_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `inix6848_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `inix6848_db`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `inix6848_db`;
INSERT INTO `inix6848_db`.`user` (`id_user`, `username`, `password`, `registered`, `lastlogin`, `role`) VALUES (1, 'administrator', 'K-softDev', '2015-07-21', '2015-07-21', 'administrator');

COMMIT;

